/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.altimetrik.inventoryManagement.controllerInterface;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.altimetrik.inventoryManagement.model.Inventory;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
import io.swagger.annotations.AuthorizationScope;

@Api(value = "inventory", description = "the inventory API")
public interface InventoryApi {

    @ApiOperation(value = "Update an existing inventory", nickname = "updateInventory", notes = "this is to update inventory in the system", response = Inventory.class, authorizations = {
        @Authorization(value = "inventoryManagement_auth", scopes = {
            @AuthorizationScope(scope = "write:inventorys", description = "modify inventorys in your account"),
            @AuthorizationScope(scope = "read:inventorys", description = "read your inventorys")
            })
    }, tags={ "inventory", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Inventory.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "inventory not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/inventory",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    ResponseEntity<Inventory> updateInventory(@ApiParam(value = "inventory object that needs to be updated to the inventory system" ,required=true )  @Valid @RequestBody Inventory body);

}
